### ISSUE TITLE
Add man pages

### ISSUE THREAD

**Issue by musicinmybrain** [bramstein/sfnt2woff-zopfli#12]
I wrote man pages ([zip file, attached](https://github.com/bramstein/sfnt2woff-zopfli/files/5527215/man-pages.zip)) based on the help output from the two binaries. Man pages are useful; please consider distributing these in the source tarball.

**Comment by bramstein** [comment]
Thanks, I like this idea, but know very little about man pages. Do I just add the files to the root of the project?

**Comment by musicinmybrain** [comment]
> Thanks, I like this idea, but know very little about man pages. Do I just add the files to the root of the project?

Since the `Makefile` doesn’t attempt to provide an install target, that’s probably the best choice. I’ll create a quick PR that does just that.

Those who want to use them (like me—now that #10 is merged, I’ll probably package this project for Fedora Linux) will know what to do with them.
